package com.xiaolinzi.shardingsphere.study.mapper;


import java.util.List;

import com.xiaolinzi.shardingsphere.study.entity.TestUser02;
import com.xiaolinzi.shardingsphere.study.entity.TestUser02Example;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestUser02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    long countByExample(TestUser02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int deleteByExample(TestUser02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int insert(TestUser02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int insertSelective(TestUser02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    List<TestUser02> selectByExample(TestUser02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    TestUser02 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TestUser02 record, @Param("example") TestUser02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TestUser02 record, @Param("example") TestUser02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestUser02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user02
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestUser02 record);
}